### Get All Comments
GET http://localhost:3000/comments

### Make a Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "text": "New Comment"
}

### Get a Comment by ID
GET http://localhost:3000/comments/1

### Update a Comment by ID
PATCH http://localhost:3000/comments/3
Content-Type: application/json

{
  "text": "Updated Comment"
}
