### Get All Comments
GET http://localhost:3000/comments

### Get Comments by Query
GET http://localhost:3000/comments?query=ir

### Make a Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "text": "New Comment"
}

### Get a Comment by ID
GET http://localhost:3000/comments/1

### Update a Comment by ID
PATCH http://localhost:3000/comments/3
Content-Type: application/json

{
  "text": "Updated Comment"
}

### Delete a Comment by ID
DELETE http://localhost:3000/comments/3

### Access Profile API
GET http://localhost:3000/profile/api
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

### Get the Current Date
GET http://localhost:3000/time

### Get Categories
GET http://localhost:3000/categories
